sudo: required

language: node_js
node_js: "0.12"

cache:
  directories:
  - node_modules

services:
- docker

before_install: "make install"

script: "make clean all"

after_script: "make deploy-html" 

env:
  global:
  - secure: cO4bDza/9iSsUGVPTJzbl5vXxrr6e0oFgLngqrQcXGcqfJcEvkpKh0xC2Q8d67KixtKnb3TEqOIw/WIKVmTkAVSpLWxtuIu/SNaMQIAbjcNqLhzMeP/s8q5CqeOgAUbVjJB/WKwcr4ZwU4c2ndnwMqU96Sa5RZrBj8vmbFLdMH4=
